### ISSUE TITLE
Relationship with https://github.com/daveshields/jikespg ?

### ISSUE THREAD

**Issue by mickaelistria** [A-LPG/LPG2#4]
I'm trying to learn a bit more about the world of parser generators. I know Eclipse JDT uses jikespg (an old 1.3 version) to generate the parser ( https://www.eclipse.org/jdt/core/howto/generate%20parser/generateParser.html ), I also found https://github.com/daveshields/jikespg ; and then this repo says "The LALR parser generator (LPG also known as JikePG)".
So do you think that the parser generator here could be usable an alternative to jikespg in Eclipse, using the same grammar file ( https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.compiler.batch/grammar/java.g ) and lead to same -or better- result?

**Comment by kuafuwang** [comment]
lpg2 and jikespg write by Philiphe Charles.

This  project is a fork of [LPG](https://sourceforge.net/projects/lpg/) which create  by: [Philiphe Charles](https://daveshields.wordpress.com/2009/04/04/a-programmers-programmer-philippe-charles/), [Robert M. Fuhrer ](https://www.linkedin.com/in/robertmfuhrer/), Gerry Fisher. But It didn't update 
since  2013-04-25. We are the user of this tool. We want to update this tool , so we fork it and update it here.the original fork only support  java runtime . We brought the lsp server , vscode extend ,other language runtime for LPG2 .

[JikesPG compatibility](https://sourceforge.net/p/lpg/discussion/523519/thread/360743ac/)  had been discussued.

**Comment by kuafuwang** [comment]
https://github.com/daveshields/jikespg is  af fork of jikespg.
